name: Validate terraform fmt
on:
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    name: terraform fmt check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for accurate diffs
      - name: Get modified Terraform files
        id: modified_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}:${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} -- '*.tf' | tr '\n' ' ' | sed 's/ $//' > modified_files.txt
          echo "MODIFIED_FILES=$(cat modified_files.txt)" >> $GITHUB_ENV
      - name: Configure terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Validate terraform fmt (modified files)
        run: |
          set -e
          if [[ -n "$MODIFIED_FILES" ]]; then
            for changed_file in $MODIFIED_FILES; do
              echo "Checking terraform fmt on ${changed_file}..."
              terraform fmt -check $changed_file
              FMT_STATUS=$(echo $?)
              if [[ $FMT_STATUS -ne 0 ]]; then
                echo "âŒ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
                exit 1 # Exit immediately on failure
              fi
            done
          else
            echo "No modified Terraform files found."
          fi
